#!/usr/bin/env bash

action=$1

if [[ "$action" != "-n" && "$action" != "-p" ]]; then
    printf "\naction missing (-n|-p)\n\n"
    exit
fi

current_path=$(basename $2)
if [ -z $current_path ]; then
    current_dir=$(pwd)
else
    current_dir="$(pwd)/$(dirname $2)"
fi

i=0
pointer=-1
list=$(ls -lt -r $current_dir | awk '{print $9}')
current_dir=$(echo $current_dir | sed 's/\/\.//g')
for x in $list;do
    if [[ -f $x ]]; then
        base_cp=$(basename $current_path)
        base_x=$(basename $x)
        if [[ $base_cp == $base_x ]];then
            pointer=$i
        fi
        i=$((i+1))
    fi
done

i=0
for x in $list;do
    if [[ -f $x || -f $current_dir/$x ]]; then
        if [[ $x != $current_dir* ]]; then
            x=$current_dir/$x
        fi
        if [[ $i == $((pointer+1)) && $action == "-n" ]];then
            echo $x
        fi
        if [[ $i == $((pointer-1)) && $action == "-p" ]];then
            echo $x
        fi
        i=$((i+1))
    fi
done
