#!/usr/bin/env bash

action=$1

if [[ "$action" != "-n" && "$action" != "-p" ]]; then
    printf "\naction missing (-n|-p)\n\n"
    exit
fi

current_path=$(basename $2)
if [ -z $current_path ]; then
    current_dir=$(pwd)
else
    dirname2=$(dirname $2)
    if [[ $dirname2 != $pwd* ]]; then
        dirname2="$(pwd)/$dirname2"
    fi
    current_dir=$dirname2
fi

i=0
pointer=-1
list=$(ls -lt -r $current_dir | awk '{print $9}')
current_dir=$(echo $current_dir | sed 's/\/\.//g')
for x in $list;do
    if [[ -f $x || -f $current_dir/$x ]]; then
        base_cp=$(basename $current_path)
        base_x=$(basename $x)
        if [[ $base_cp == $base_x ]];then
            pointer=$i
        fi
        i=$((i+1))
    fi
done

i=0
for x in $list;do
    file=$x 
    if [[ -f $current_dir/$x ]]; then
        file=$current_dir/$x
    fi
    if [[ -f $file ]]; then
        if [[ $i == $((pointer+1)) && $action == "-n" ]];then
            echo $file
        fi
        if [[ $i == $((pointer-1)) && $action == "-p" ]];then
            echo $file
        fi
        i=$((i+1))
    fi
done
